# Generated by Django 5.2.7 on 2025-10-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bird_family_bird_sighted_sighting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='common_region',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bird',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
