# Generated by Django 5.2.7 on 2025-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bird_common_region_bird_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
