# Generated by Django 5.2.7 on 2025-10-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_bird_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bird',
            name='sighted',
        ),
        migrations.AddField(
            model_name='sighting',
            name='birds',
            field=models.ManyToManyField(to='main_app.bird'),
        ),
    ]
