# Generated by Django 5.2.7 on 2025-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_sighting_birds_sightingbird'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='birds',
            field=models.ManyToManyField(through='main_app.SightingBird', to='main_app.bird'),
        ),
    ]
